#!/data/data/com.termux/files/usr/bin/bash

echo "=========================================="
echo "  Guia Rápido - Minecraft Server Termux"
echo "  PocketMine-MP (ARM64 Nativo)"
echo "=========================================="
echo ""
echo "📋 PASSO A PASSO:"
echo ""
echo "1️⃣  PRIMEIRA VEZ (fazer apenas uma vez):"
echo "    ./install.sh"
echo ""
echo "2️⃣  INICIAR SERVIDOR:"
echo "    ./start.sh"
echo ""
echo "3️⃣  PARAR SERVIDOR:"
echo "    Ctrl+C no terminal do servidor"
echo "    OU execute: ./stop.sh"
echo ""
echo "=========================================="
echo ""
echo "❓ PROBLEMAS COMUNS:"
echo ""
echo "🔴 Erro: 'bedrock_server not found'"
echo "   Solução: Execute ./install.sh primeiro!"
echo "   (Agora usa PocketMine-MP, não servidor oficial)"
echo ""
echo "🔴 Erro: 'Port 3000 already in use'"
echo "   Solução: Execute ./stop.sh e tente novamente"
echo ""
echo "🔴 Servidor não conecta"
echo "   Solução: Aguarde 1-2 minutos após iniciar"
echo "            Verifique as URLs no console"
echo ""
echo "=========================================="
echo ""
echo "🆘 COMANDOS ÚTEIS:"
echo ""
echo "  ./stop.sh          - Para todos os processos"
echo "  ./commands.sh      - Menu interativo"
echo "  ./install.sh       - Reinstalar servidor"
echo ""
echo "=========================================="
echo ""
